### ISSUE TITLE
GUI choice

### ISSUE THREAD

**Issue by DarkmatterVale** [DarkmatterVale/JARVIS#15]
JARVIS's UI will be a GUI. A decision has to be made however on what library is used. I have used TKinter before, and I do not think that is very modern. I am currently leaning towards Kivy, although that will require a separate installation process.

Anyone else have any thoughts?

**Comment by gunthercox** [comment]
Kivy seems very modern and looks like it would be a good choice.

Also, have you considered setting this up as a web application? You could do the processing in the background with something like django and build a web based gui to access it. Then it could run locally on a computer, or be scaled up to be hosted on a server if you ever chose to do so.

**Comment by DarkmatterVale** [comment]
I have considered creating this as a web application. I originally thought about using Electron ( http://electron.atom.io ), but my thought process was that seemed to be too much work :) . I will check out Django. Thank you for the help (and let me know if you would want to help do some coding....)!

**Comment by gunthercox** [comment]
No problem. Let me know if there is anything I can help out with. I also have a good amount of experience with django if you choose to go that route.

**Comment by DarkmatterVale** [comment]
Django looks like a great idea; much better than Kivy. After doing some work, I have a test site (albeit completely unrelated to this).

I need to get a prototype of the site working first, but then I would really appreciate any help you are willing to provide. Thanks!

**Comment by DarkmatterVale** [comment]
This is related to a chat site since we will be using Django, so I'm gonna close this issue.
